local opts = {
    backup = false,
    clipboard = "unnamedplus",
    cmdheight = 1,
    fileencoding = "utf-8",
    hlsearch = true,
    ignorecase = true,
    mouse = "a",
    pumheight = 10,
    smartcase = true,
    smartindent = true,
    swapfile = false,
    termguicolors = true,
    timeoutlen = 500,
    undofile = true,
    updatetime = 200,
    writebackup = false,
    expandtab = true,
    shiftwidth = 4,
    tabstop = 4,
    cursorline = true,
    cursorcolumn = false,
    number = true,
    relativenumber = false,
    numberwidth = 4,
    signcolumn = "yes",
    wrap = false,
    scrolloff = 8,
    sidescrolloff = 8,
    spell = false,
}

for k, v in pairs(opts) do
  vim.opt[k] = v
end
